scheme_version: 1
token: i-am-token
os:
  ssh_authorized_keys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDoITw/rO25GOJqcjziveizqQGdAhWDkpjmv+2P2XEhtYoFgQ5YBtUNXHA24HD/SWWiY27FQl5i9IYtz+pwglxwYqJCl4SmUlOqZLLMhnr0YMSq05vLN0WcvKkKDO6TDpsXHsTkge+89dQMdkdzOXdxvtmijWj2lG8yfuW7Uuy7Bn21OY4M2ZFJDQHv+imS2BrhCPlVkJiQjgNIlDhu7iizIzqV3wiB2kcR0B7tYNEaL4FaJGxWN9H2efwteiCaHBhOu+GetTyqY4KL/G0AoyadnTxeBZgQVjQlSvbIYOgTN+cAp5zKP0UoYbZ7o/eId3X8z4cZYzw3OenaxP8y5fH5SIkwo1YBcq5CWMqYQrZtWPU60SpuGQVUw8GtjbUm45CXsbQUFOhfMy2vWTsxPLvkZu9uVevRvJt3ZPu1iacFK1kx3QlVQESjp3h4nyu4ypRvfNGafaBfdv516L3LStZCt40PvY2iEx38SzUKPik3sLSti71J9i04UAeFEjZt7HGqihjetQ3yiOY8QioTopYXhAlUDsEsDTWwecysWXVgmlWPbx0aNi1vS6NkQ/RE6PHzWldMV4s9VARs3YZAreAzMAWhO9DKx6WyrQh6kv5C8K1cPnnu/BkG8rsAcXtZ/KwX9pxyiupJRK+SK1iwKD+w1hdQtg1cjL9gRkAVuHNMLw==
    - github:nnewc
    - ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFGa1ZQ0g52E6K5N3eq9S8pTgqDq7QfHbgdJ1UuXQFPasmT35lHyD+pBZd8aaN1AdI2b6dj/VY9nwDa6NlC0bIw=
  hostname: harvey01
  password: rancher
  dns_nameservers:
    - 192.168.60.1
  ntp_servers:
    - 0.suse.pool.ntp.org
    - 1.suse.pool.ntp.org
  after_install_chroot_commands:
  - echo 'source <(kubectl completion bash)' >> /root/.bashrc
  write_files:
  - path: /var/lib/rancher/rke2/server/manifests/excoredns.yaml
    content: |
      apiVersion: helm.cattle.io/v1
      kind: HelmChart
      metadata:
        namespace: kube-system
        name: excoredns
      spec:
        targetNamespace: kube-system
        chart: k8s-gateway
        repo: https://ori-edge.github.io/k8s_gateway
        valuesContent: |-
          domain: harvey.lan
          watchedResources:
          - Ingress
          service:
            loadBalancerIP: 192.168.60.3
  - path: /var/lib/rancher/rke2/server/manifests/nvme.yaml
    content: |
      apiVersion: apps/v1
      kind: DaemonSet
      metadata:
        name: nvme-exporter
        namespace: cattle-monitoring-system
      spec:
        selector:
          matchLabels:
            app: nvme-exporter
        template:
          metadata:
            labels:
              app: nvme-exporter
          spec:
            tolerations:
            - key: node-role.kubernetes.io/master
              operator: Exists
              effect: NoSchedule
            containers:
            - name: nvme-exporter
              image: "fritchie/nvme_exporter"
              command: ["nvme_exporter"]
              # nvme-cli requires pod to be privileged
              securityContext:
                privileged: true
              ports:
              - containerPort: 9998
                protocol: TCP
      ---
      apiVersion: monitoring.coreos.com/v1
      kind: ServiceMonitor
      metadata:
        name: nvme-exporter
        namespace: cattle-monitoring-system
        labels:
          app: nvme-exporter
      spec:
        selector:
          matchLabels:
            app: nvme-exporter
        endpoints:
        - port: metrics
          path: /metrics
  - path: /var/lib/rancher/rke2/server/manifests/harbor.yaml
    content: |
      apiVersion: helm.cattle.io/v1
      kind: HelmChart
      metadata:
        namespace: kube-system
        name: harbor
      spec:
        targetNamespace: harbor
        createNamespace: true
        chart: harbor
        repo: https://helm.goharbor.io
        valuesContent: |-
          persistence:
            enabled: true
          expose:
            type: ingress
            ingress:
              annotations:
                ingress.kubernetes.io/proxy-body-size: '0'
                ingress.kubernetes.io/ssl-redirect: 'true'
                nginx.ingress.kubernetes.io/proxy-body-size: '0'
                nginx.ingress.kubernetes.io/ssl-redirect: 'true'
                cert-manager.io/issuer: selfsigned-issuer
              hosts:
                core: harbor.harvey.lan
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
          tls:
            certSource: secret
            enabled: true
            secret:
              secretName: tls-ingress-harbor
          externalURL: https://harbor.harvey.lan
install:
  automatic: true
  mode: create
  role: default
  harvester:
    storage_class:
      replica_count: 1
  debug: true
  device: /dev/nvme1n1
  data_disk: /dev/nvme0n1
  skipchecks: true
  tty: tty1
  management_interface:
    interfaces:
    - name: enp89s0
    method: dhcp
    bondoptions:
      miimon: "100"
      mode: active-backup
  vip: 192.168.60.155
  vip_mode: static
  iso_url: http://192.168.1.6:8083/asset-mirror/releases/download/carbide/harvester/v1.3.2-govt.1/harvester-v1.3.2-govt.1-amd64.iso
  addons:
    harvester_vm_import_controller:
      enabled: false
      values_content: ""
    harvester_pcidevices_controller:
      enabled: false
    rancher_monitoring:
      enabled: true
    rancher_logging:
      enabled: true
    harvester_seeder:
      enabled: false
system_settings:
  auto-disk-provision-paths: ""
