scheme_version: 1
token: i-am-token
os:
  ssh_authorized_keys:
    - github:nnewc
    - ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFGa1ZQ0g52E6K5N3eq9S8pTgqDq7QfHbgdJ1UuXQFPasmT35lHyD+pBZd8aaN1AdI2b6dj/VY9nwDa6NlC0bIw=
  hostname: harv_node
  password: rancher
install:
  mode: create
  device: /dev/sda
  data_disk: /dev/sdb
  skipchecks: true
  wipedisks: true
  addons:
    harvester_vm_import_controller:
      enabled: false
      values_content: ""
    harvester_pcidevices_controller:
      enabled: false
    rancher_monitoring:
      enabled: true
    rancher_logging:
      enabled: true
    harvester_seeder:
      enabled: false
system_settings:
  auto-disk-provision-paths: ""
